///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UsersDataLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
} 
*/

  String? url;
  String? label;
  bool? active;

  UsersDataLinks({
    this.url,
    this.label,
    this.active,
  });
  UsersDataLinks.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    label = json['label']?.toString();
    active = json['active'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['label'] = label;
    data['active'] = active;
    return data;
  }
}

class UsersDataData {
/*
{
  "id": 107,
  "first_name": "pixbit",
  "last_name": "solutions",
  "join_date": "2021-08-06T00:00:00.000000Z",
  "date_of_birth": "2021-08-25T00:00:00.000000Z",
  "designation_id": 1,
  "gender": "male",
  "mobile": 999999999,
  "landline": 1111111,
  "email": "pix@gmail.com",
  "present_address": "ss",
  "permanent_address": "sds",
  "profile_picture": "1631789305.jpeg",
  "resume": "1631789305.pdf",
  "created_at": "2021-09-16T00:00:00.000000Z",
  "updated_at": "2022-03-23T00:00:00.000000Z",
  "status": "TEMPORERY"
} 
*/

  int? id;
  String? firstName;
  String? lastName;
  String? joinDate;
  String? dateOfBirth;
  int? designationId;
  String? gender;
  int? mobile;
  int? landline;
  String? email;
  String? presentAddress;
  String? permanentAddress;
  String? profilePicture;
  String? resume;
  String? createdAt;
  String? updatedAt;
  String? status;

  UsersDataData({
    this.id,
    this.firstName,
    this.lastName,
    this.joinDate,
    this.dateOfBirth,
    this.designationId,
    this.gender,
    this.mobile,
    this.landline,
    this.email,
    this.presentAddress,
    this.permanentAddress,
    this.profilePicture,
    this.resume,
    this.createdAt,
    this.updatedAt,
    this.status,
  });
  UsersDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    joinDate = json['join_date']?.toString();
    dateOfBirth = json['date_of_birth']?.toString();
    designationId = json['designation_id']?.toInt();
    gender = json['gender']?.toString();
    mobile = json['mobile']?.toInt();
    landline = json['landline']?.toInt();
    email = json['email']?.toString();
    presentAddress = json['present_address']?.toString();
    permanentAddress = json['permanent_address']?.toString();
    profilePicture = json['profile_picture']?.toString();
    resume = json['resume']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['join_date'] = joinDate;
    data['date_of_birth'] = dateOfBirth;
    data['designation_id'] = designationId;
    data['gender'] = gender;
    data['mobile'] = mobile;
    data['landline'] = landline;
    data['email'] = email;
    data['present_address'] = presentAddress;
    data['permanent_address'] = permanentAddress;
    data['profile_picture'] = profilePicture;
    data['resume'] = resume;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['status'] = status;
    return data;
  }
}

class UsersData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 107,
      "first_name": "pixbit",
      "last_name": "solutions",
      "join_date": "2021-08-06T00:00:00.000000Z",
      "date_of_birth": "2021-08-25T00:00:00.000000Z",
      "designation_id": 1,
      "gender": "male",
      "mobile": 999999999,
      "landline": 1111111,
      "email": "pix@gmail.com",
      "present_address": "ss",
      "permanent_address": "sds",
      "profile_picture": "1631789305.jpeg",
      "resume": "1631789305.pdf",
      "created_at": "2021-09-16T00:00:00.000000Z",
      "updated_at": "2022-03-23T00:00:00.000000Z",
      "status": "TEMPORERY"
    }
  ],
  "first_page_url": "http://training.pixbit.in/api/employees?page=1",
  "from": 1,
  "last_page": 2,
  "last_page_url": "http://training.pixbit.in/api/employees?page=2",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": "http://training.pixbit.in/api/employees?page=2",
  "path": "http://training.pixbit.in/api/employees",
  "per_page": 10,
  "prev_page_url": null,
  "to": 10,
  "total": 11
} 
*/

  int? currentPage;
  List<UsersDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<UsersDataLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  UsersData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  UsersData.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <UsersDataData>[];
      v.forEach((v) {
        arr0.add(UsersDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json['first_page_url']?.toString();
    from = json['from']?.toInt();
    lastPage = json['last_page']?.toInt();
    lastPageUrl = json['last_page_url']?.toString();
    if (json['links'] != null) {
      final v = json['links'];
      final arr0 = <UsersDataLinks>[];
      v.forEach((v) {
        arr0.add(UsersDataLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json['next_page_url']?.toString();
    path = json['path']?.toString();
    perPage = json['per_page']?.toInt();
    prevPageUrl = json['prev_page_url']?.toString();
    to = json['to']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['first_page_url'] = firstPageUrl;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['last_page_url'] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['links'] = arr0;
    }
    data['next_page_url'] = nextPageUrl;
    data['path'] = path;
    data['per_page'] = perPage;
    data['prev_page_url'] = prevPageUrl;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class Users {
/*
{
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 107,
        "first_name": "pixbit",
        "last_name": "solutions",
        "join_date": "2021-08-06T00:00:00.000000Z",
        "date_of_birth": "2021-08-25T00:00:00.000000Z",
        "designation_id": 1,
        "gender": "male",
        "mobile": 999999999,
        "landline": 1111111,
        "email": "pix@gmail.com",
        "present_address": "ss",
        "permanent_address": "sds",
        "profile_picture": "1631789305.jpeg",
        "resume": "1631789305.pdf",
        "created_at": "2021-09-16T00:00:00.000000Z",
        "updated_at": "2022-03-23T00:00:00.000000Z",
        "status": "TEMPORERY"
      }
    ],
    "first_page_url": "http://training.pixbit.in/api/employees?page=1",
    "from": 1,
    "last_page": 2,
    "last_page_url": "http://training.pixbit.in/api/employees?page=2",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": "http://training.pixbit.in/api/employees?page=2",
    "path": "http://training.pixbit.in/api/employees",
    "per_page": 10,
    "prev_page_url": null,
    "to": 10,
    "total": 11
  }
} 
*/

  UsersData? data;

  Users({
    this.data,
  });
  Users.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? UsersData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
